### ISSUE TITLE
Remove pack/unpack from micro_mg

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/PUMAS#9] opened 2020-10-28 20:40 UTC
Remove the pack/unpack structures from PUMAS in conjunction with removing from CAM

**Comment by andrewgettelman** [comment] 2020-10-28 20:47
Is there any packing/unpacking in PUMAS? Since micro_mg_cam.F90 is a CAM issue, I think most of it lies there. But I've assigned this to you. I will try to up your PUMAS privileges next.

**Comment by cacraigucar** [comment] 2020-10-28 20:50
It may be as simple as removing micro_pumas_data.F90 from PUMAS.  This module has the guts of the pack/unpack routines.  As soon as my research indicated I'd be touching PUMAS, I opened the issue.

**Comment by andrewgettelman** [comment] 2020-10-28 21:03
Okay. Thanks for doing this. Let me know if you need any more permissions or anything on PUMAS.

**Comment by cacraigucar** [comment] 2020-11-10 20:27
@Katetc and @andrewgettelman   I believe that I have run into an issue with removing the pack/unpack which will require another change in PUMAS.  I am happy to implement the change in the PR which I will be opening for this issue.  Before I make this change, I wanted to run it by you both.

The problem is that micro_mg_tend in micro_mg3_0 only has one variable for dimension, mgncol.  This is used to describe the extent of the arrays and for allocating new arrays.  Loops then happen over all of mgncol.  This results in problems when in CAM ncol /=pcols.  This behavior was fine in the pack/unpack realm, as mgncol was always the same size as the array sizes and the extent of useful data.  In micro_mg1_0, which was developed before pack/unpack, ncol and pcols are both passed in and used appropriately. 

I believe that I need to modify micro_mg3_0 to include both a pcols and ncol.  If you agree, please suggest what you want the names to be.  I expect that mgncol probably is the name for ncol.

**Comment by andrewgettelman** [comment] 2020-11-10 20:45
Can you explain why we need both dimensions? I recall it has to do with the last chunk not being the same as the total length of the arrays. 

This seems very CAM specific. Is there a way to generalize the interface to pass the number of columns needed and have it vary across chunks, say by calling a routine that tells you the size of the arrays by chunk?

Since this will all be removed when we get to the CCPP, it seems unwise now to add it to PUMAS if we can avoid it.

Thanks,

Andrew

**Comment by gold2718** [comment] 2020-11-10 21:22
The issue is that the input/output arrays in `micro_mg_tend` are Fortran 77 arrays (e.g., `qcn(mgncol,nlev)`) instead of Fortran 90 arrays (e.g., `qcn(:,:)`. This means that when `mgncol < pcols`, you will get the wrong data into `micro_mg_tend`.

You could fix this in the call from `micro_mg_cam_tend` (e.g., replace `qc` with `qc(:ncol,:)`), however, this would generate a copy for every array which would put us back to the worse performance than either the current packed or the old, unpacked implementation.

If you change the dummy argument array declarations to be Fortran 90, I think the problem goes away.

**Comment by andrewgettelman** [comment] 2020-11-10 21:28
Thanks Steve,

"If you change the dummy argument array declarations to be Fortran 90, I think the problem goes away."

So is this the solution? So how do we do that?

**Comment by cacraigucar** [comment] 2020-11-10 21:53
I can make this change to the dummy array declarations in my PR, if you approve.

**Comment by gold2718** [comment] 2020-11-10 21:57
Most of the work would be in just converting the dummy array declarations (all the lines with `intent(in)` or `intent(out)`) to use colons instead of explicit dimensions. There are a few other places where assignments need to be adjusted. For instance:
```
    qc = qcn
```
becomes
```
    qc(:mgncol,:) = qcn(:mgncol,:)
```

This would also apply to subroutines such as `calc_rercld`.

This approach should not require any changes in how the code is called.

**Comment by cacraigucar** [comment] 2020-11-10 22:05
As Steve said, these changes will be internal and not effect the calling sequence.  Since I am testing the pack/unpack, the subsequent PR will contain tested code.

**Comment by andrewgettelman** [comment] 2020-11-10 22:44
Thanks! Then this all sounds fine. I assume from the thread that the fix is internal and does not suffer from the performance hit Steve mentioned with changing the call. It also looks like it does not require pcol and ncol to be in the micro_mg routines, but only mgncol. That's great. Thanks!

**Comment by Katetc** [comment] 2020-11-10 22:46
Hi everybody, this all sounds fine to me. I'm just super excited to not have the packing in any more. I'm ok with (almost) any changes required to get rid of it.

**Comment by andrewgettelman** [comment] 2022-05-18 04:13
This was completed in cam6_3_057

**Comment by cacraigucar** [comment] 2022-05-18 14:55
@andrewgettelman - I believe that micro_pumas_data.F90 still needs to be removed from the PUMAS repository.

**Comment by andrewgettelman** [comment] 2022-05-18 14:59
Thanks @cacraigucar for letting me know. I'm reopening and adding @Katetc  so we can remove this at the next checkin for PUMAS (which should be soon: see new issue on updates).  Thanks!

**Comment by andrewgettelman** [comment] 2022-07-07 22:23
Completed.

**Closed as completed by andrewgettelman** 2022-07-07 22:23 UTC
